---
title: "Canonical Correlation Analysis"
author: "2020111538 Oh SukJu"
date: 
output:
  github_document:
    latex_engine: xelatex
    keep_tex: false
    toc: true            # 목차 추가
    toc_depth: 3         # 목차의 깊이 지정
    number_sections: true  # 섹션 번호 지정
    fig_caption: true    # 그림 캡션 추가
    fig_width: 6         # 그림 너비
    fig_height: 4        # 그림 높이
    includes:
      in_header:
  output: 
---

```{r}
library(MASS)
library(Matrix)
pp=3
set.seed(2022)
Sigma = matrix(rWishart(1,pp,diag(pp)), pp)
R1 = diag(1/sqrt(diag(Sigma)))%*%Sigma%*%diag(1/sqrt(diag(Sigma)))

Sigma = matrix(rWishart(1,pp,diag(pp)), pp)
R2 = diag(1/sqrt(diag(Sigma)))%*%Sigma%*%diag(1/sqrt(diag(Sigma)))

round(R1,2)

```
```{r}
round(R2,2)
```

```{r}
nn=10000
SS=bdiag(R1,R2)
SS

PP2=dim(SS)[1]
mu=rep(0,PP2)
set.seed(2022)
d1=mvrnorm(nn,mu,SS)
round(cor(d1),2)
```


```{r}
#update.packages(ask=F)
#install.packages('CCA')
library(CCA)
```

```{r}
d1=d1[,as.numeric(matrix(1:PP2,2,byrow=T))]
d1=data.frame(d1)
names(d1)=paste('X',1:PP2,sep='')
round(cor(d1),2)
```


```{r}
X=d1[,1:3]
Y=d1[,-c(1:3)]
print(matcor(X,Y), digit=2)
```

```{r}
ss=cov(d1)
sxx=ss[1:3,1:3]
sxy=ss[1:3,4:6]
syy=ss[4:6,4:6]

tmp=eigen(solve(sxx)%*%sxy%*%solve(syy)%*%t(sxy)) ;tmp

```
```{r}
v=tmp$vectors

sxx

```

```{r}
tmp=eigen(sxx)
sxx2=tmp$vectors%*%diag(sqrt(tmp$values))%*%t(tmp$vectors)

sxx2%*%sxx2
```

```{r}
tmp=eigen(syy)
syy2=tmp$vectors%*%diag(sqrt(tmp$values))%*%t(tmp$vectors)
u = eigen(solve(sxx)%*%sxy%*%solve(syy)%*%t(sxy))$vectors
P=sxx2%*%u
Q=syy2%*%v
```


```{r}
d2=cc(X,Y)
round(d2$xcoef,2);round(u,2);round(P,2)
```

```{r}
tmp=eigen(solve(sxx)%*%sxy%*%solve(syy)%*%t(sxy))
u=tmp$vectors
l=diag(tmp$values)

solve(sxx)%*%sxy%*%solve(syy)%*%t(sxy)


```

```{r}
u%*%l%*%t(u)
```

```{r}
ss=cov(d1)
sxx=ss[1:3,1:3]
sxy=ss[1:3,4:6]
syy=ss[4:6,4:6]
tmp=eigen(sxx)

sxx2=tmp$vectors%*%diag(sqrt(tmp$values))%*%t(tmp$vectors)
tmp
syy2=tmp$vectors%*%diag(sqrt(tmp$values))%*%t(tmp$vectors)

tmp=solve(sxx2)%*%sxy%*%solve(syy)%*%t(sxy)%*%solve(sxx2)
tmp

```

```{r}
tmp=eigen(tmp)
p=tmp$vectors
l=diag(tmp$values)
p%*%l%*%t(p)

```

```{r}
ss=cov(d1)
sxx=ss[1:3,1:3]
sxy=ss[1:3,4:6]
syy=ss[4:6,4:6]
tmp=eigen(sxx)
sxx2=tmp$vectors%*%diag(sqrt(tmp$values))%*%t(tmp$vectors)

tmp=eigen(syy)
syy2=tmp$vectors%*%diag(sqrt(tmp$values))%*%t(tmp$vectors)

tmp=solve(sxx2)%*%sxy%*%solve(syy)%*%t(sxy)%*%solve(sxx2)


tmp=eigen(tmp)

P=tmp$vectors
u=solve(sxx2)%*%P
tmp=solve(syy2)%*%t(sxy)%*%solve(sxx)%*%sxy%*%solve(syy2)

tmp=eigen(tmp)

Q=tmp$vectors
v=solve(syy2)%*%Q
```

```{r}
d2=cc(X,Y)
round(d2$xcoef,4);round(u,4)
```

```{r}
round(d2$ycoef,4);round(v,4)
```

```{r}
ss=cov(d1)
sxx=ss[1:3,1:3]
sxy=ss[1:3,4:6]
syy=ss[4:6,4:6]
geigen(sxy,sxx,syy)
```

```{r}
v
```

```{r}
d2$cor
```

```{r}
d2$scores$corr.X.xscores
```
```{r}
#install.packages('CCP')
library(CCP)
nn=dim(d1)[1]
x=d1[,1:3]
y=d1[,-c(1:3)]
p.asym(d2$cor,dim(x)[1],dim(x)[2], dim(y)[2],tstat='Wilks')

# M = 2
```











