---
title: "main factor analysis 2"
author: "2020111538 Oh SukJu"
date: 
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: false
    toc: true            # 목차 추가
    toc_depth: 3         # 목차의 깊이 지정
    number_sections: true  # 섹션 번호 지정
    fig_caption: true    # 그림 캡션 추가
    fig_width: 6         # 그림 너비
    fig_height: 4        # 그림 높이
    includes:
      in_header:
  output: 
---

```{r}
rr=matrix(c(  1,  0.6,  0.1, -0.1,

            0.6,    1,  0.2, -0.2,

            0.1,  0.2,    1, 0.7,
            -0.1, -0.2, 0.7, 1.0 ),nrow=4,byrow=T)

D=diag(c(1,2,.4, 2))

Sigma=D^{1/2}%*%rr%*%D^{1/2}

rr;Sigma

# ss;rr;Sigma

```

```{r}
library(MASS)
nn=10000

mu=rep(0,4)

set.seed(320)

d1=mvrnorm(nn,mu,Sigma)

d1 <- scale(d1)
```

```{r}
R = cov(d1)
eeR = eigen(R)
print(eeR)
cumsum(eeR$values) / sum(eeR$values) * 100
```

```{r}
d1 <- as.matrix(d1)
P=d1%*%eeR$vectors[,1:2]
P=data.frame(P)
head(d1)
par(mfrow=c(2,2))
plot(d1[,1], d1[,2], pch=19, col='grey', cex = .2, xlab="1st variable", ylab="2nd variable")
plot(d1[,1], d1[,3], pch=19, col='grey', cex = .2, xlab="1st variable", ylab="4th variable")
plot(d1[,3], d1[,4], pch=19, col='grey', cex = .2, xlab="3rd variable", ylab="4th variable")
plot(P$X1, P$X2, pch=19, col="grey", cex=.2, xlab="1st po", ylab="2nd pc")
```

```{r echo-FALSE, warning=FALSE}
P=d1%*%eeR$vectors[,1:3]
p=data.frame(P)

```

```{r}
X1 <- P[,1]
X2 <- P[,2]
X3 <- P[,3]


library(plotly)
plot_ly(x=X1, y=X2, z=X3, type = "scatter3d", width=8, height=8, mode='markers', marker=list(size=.8))
for(i in 1:22) print(cbind(X1,X2,X3))
```

```{r}
eeR
p=4
sum(eeR$values>0) ==p
```

```{r}
d1.pc=prcomp(d1)
d1.pc
#plot(d1.pc)
str(d1.pc)
summary(d1.pc)
```

```{r}
biplot(d1.pc, pch=19, cex=0.6, scale=T, lwd=3)
```

```{r}
eeR
```

```{r}
d1.pca = princomp(d1)
str(d1.pca)
```

```{r}
library(MASS)
rr=matrix(c(  1,  0.6,  0.1, -0.1,

            0.6,    1,  0.2, -0.2,

            0.1,  0.2,    1, 0.7,
            -0.1, -0.2, 0.7, 1.0 ),nrow=4,byrow=T)

D=diag(c(1,2,.4, 2))

Sigma=D^{1/2}%*%rr%*%D^{1/2}

rr;Sigma

nn=10000
mm=20
mu=rep(0, dim(rr)[1])
mu2=rep(7, dim(rr)[1])
set.seed(320)
d1=rbind(mvrnorm(nn-mm,mu,Sigma), mvrnorm(mm,mu2,Sigma))
d1=scale(d1)
class(d1)
R=cov(d1)
eeR=eigen(R)
cumsum(eeR$values) / sum(eeR$values) *100

P = d1%*%eeR$vectors [,1:2]
P= data.frame(P)

X1 <- P[,1]
X2 <- P[,2]

plot(x=X1, y=X2, pch=19, col='grey', cex=.2, xlab = "lst pc", ylab = "2nd pc")

```
